/** generated by generate-component-routes.ts */
import { AccordionRouteComponent, AvatarRouteComponent, BadgeRouteComponent, ButtonRouteComponent, CardRouteComponent, ChipRouteComponent, DialogRouteComponent, DrawerRouteComponent, InputRouteComponent, ModalRouteComponent, TagRouteComponent, TooltipRouteComponent, TxtRouteComponent } from './routes/components';
import { NavRoute } from './types';

export const componentItems: NavRoute[] = [
  { title: 'Components', section: true },
  { path: 'accordion', component: AccordionRouteComponent, title: 'Accordion' },
  { path: 'avatar', component: AvatarRouteComponent, title: 'Avatar' },
  { path: 'badge', component: BadgeRouteComponent, title: 'Badge' },
  { path: 'button', component: ButtonRouteComponent, title: 'Button' },
  { path: 'card', component: CardRouteComponent, title: 'Card' },
  { path: 'chip', component: ChipRouteComponent, title: 'Chip' },
  { path: 'dialog', component: DialogRouteComponent, title: 'Dialog' },
  { path: 'drawer', component: DrawerRouteComponent, title: 'Drawer' },
  { path: 'input', component: InputRouteComponent, title: 'Input' },
  { path: 'modal', component: ModalRouteComponent, title: 'Modal' },
  { path: 'tag', component: TagRouteComponent, title: 'Tag' },
  { path: 'tooltip', component: TooltipRouteComponent, title: 'Tooltip' },
  { path: 'txt', component: TxtRouteComponent, title: 'Txt' },
];
