/**
 * Generates component documentation.
 *
 * Utility only
 */

import fs from 'fs';
import { ComponentMeta, ComponentPhase, ComponentSettings } from '../../projects/shared/src/types';
import { COMPONENT_PHASE_COLORS } from '../utils';

const TEMPLATE = (
    component: ComponentMeta & {
        phaseColor: string;
        defaultCode: string;
        imports: string[];
    },
) => `
/** Auto-generated component documentation for ${component.name}. Do not edit this file directly. */
${!component.exampleComponent ? '' : `import { NgComponentOutlet } from '@angular/common';`}
import { Component, Type } from '@angular/core';
import { ${component.imports.filter((i) => i.startsWith('UI')).join(', ')} } from '@ui/index';
import { Markup } from '../../components/markup';
${
    !component.imports.includes('Syntax')
        ? ''
        : `import { Syntax } from '../../components/syntax';
`
}import { TypeProps } from '../../components/type-props';


@Component({
    selector: 'app-component-page',
    standalone: true,
    imports: [${component.imports.join(', ')}],
    template: \`
            ${`<div ui-flex>
                <h2 style="display: flex; align-items: center; gap: 1rem;">
                   ${component.name}
                </h2>
                <span style="margin-left: auto;"><ui-tag color="${component.phaseColor}" label="${component.phase}" /></span>
            </div>
            <app-markup [source]="description" />
            
           ${
               !component.defaultCode
                   ? ''
                   : `<h3>Basic Usage</h3>
            <ui-card variant="outlined">
                <div style="display: flex;
                    align-items: center;
                    justify-content: center;
                    width: 100%;
                    border-bottom: solid 1px var(--stroke-neutral-low-contrast);
                    padding: var(--spacing-sizing-04);
                    position: relative;
                    background-color: var(--background-shade);"
                >
                    ${component.defaultCode}
                </div>
                <app-syntax
                    source="${component.defaultCode.replace(/"/g, '&quot;')}"
                    language="html"
                    style="margin-top: 2rem;"
                    [pretty]="true"></app-syntax>
            </ui-card>`
           }
            

            <h3>Inputs</h3>
            <app-type-props [props]='componentProps' />
${
    component.associatedTypes?.length
        ? `
            <h3>Associated Types</h3>
            @for (type of associatedTypes; track $index) {
                <h4>{{ type.name }}</h4>
                <app-type-props [props]="type.props" />
            }
`
        : ''
}
            ${
                !component.exampleComponent
                    ? ''
                    : `<h3>Examples</h3>
            <ng-container [ngComponentOutlet]="exampleComponent!"></ng-container>`
            }

            <h3>Stylesheet</h3>
            ${
                !component.css
                    ? `
            <p>This component does not have any specific styles.</p>`
                    : `
            <p>
                This is the CSS for the component. The css variables used within are available in the styles
                package.
            </p>
            <ui-card variant="outlined">
                <app-syntax
                    source="${component.css!}"
                    language="css"
                    style="margin-top: 2rem;"
                    [pretty]="true" />
            </ui-card>
            `
            }`.replace(/`/g, '\\`')}
            \`
})
export class ${component.name}Page {

    componentProps = ${JSON.stringify(component.inputs)};${
        component.associatedTypes?.length
            ? `
    associatedTypes = ${JSON.stringify(component.associatedTypes)};`
            : ''
    }

    description = \`${component.description.replace(/`/g, '\\`')}\`;
    
    exampleComponent: Type<any> | null = null;

   ${
       !component.exampleComponent
           ? ''
           : `
    constructor() {
        import('@ui/${component.slug}/example').then((m) => this.exampleComponent = m.${component.exampleComponent})
    }`
   }

}
`;

export const COMPONENT_PAGE_OUTPUT_DIR = 'projects/demo/src/generated/component';

export function generateComponentDocs(component: ComponentMeta, overrides?: ComponentSettings): void {
    const outputPath = `${COMPONENT_PAGE_OUTPUT_DIR}/${component.slug}.ts`;

    const imports = new Set([
        // page imports
        'UITag',
        'TypeProps',
        'UIFlexDirective',
        'Markup',
    ]);

    let defaultCode = '';

    const missingRequired = component.inputs?.filter(
        (prop) => prop.required && prop.type !== 'string' && !overrides?.defaultValues?.[prop.name],
    );

    const inputControlProps = component.inputs.filter((prop) => prop.name === 'checked' || prop.name === 'onChange');

    let skipReason = '';

    if (inputControlProps.length > 0)
        skipReason = `component has input props like checked or onChange which require handlers: ${inputControlProps.map((prop) => prop.name).join(', ')}.`;

    if (missingRequired && missingRequired.length > 0)
        skipReason = `component has required non-string inputs without default values: ${missingRequired.map((prop) => prop.name).join(', ')}.`;

    if (component.hasContent && !overrides?.ngContent)
        skipReason = 'component has ng-content and no default inputs provided.';

    // if (noProps) skipReason = 'component has no props, so default example would be the same as basic component.';

    if (component.directive) skipReason = 'component is a directive examples should be in settings file.';

    if (skipReason) {
        // eslint-disable-next-line no-console
        console.log(
            `\x1b[33m⚠️ Skipping default example generation for ${component?.file}:\n\t\t${skipReason}\x1b[0m\n`,
        );
    } else {
        imports.add(component.className);

        const propsStr: Record<string, string> = {};

        const inputValues = { ...getDefaultInputValues(component), ...overrides?.defaultValues };

        // Generate default code snippet with default inputs
        Object.entries(inputValues || {}).forEach(([name, value]) => {
            const isString =
                typeof value === 'string' && !['true', 'false'].includes(value) && /^\d+$/.test(value) === false;

            propsStr[name] = isString ? `${name}="${value}"` : `[${name}]="${value}"`;
        });

        defaultCode = `<ui-${component?.slug}\n  ${Object.values(propsStr).join('\n   ')}`;

        if (overrides?.ngContent) {
            let ngContent = '';
            if (typeof overrides.ngContent === 'string') ngContent = overrides.ngContent;
            else if (typeof overrides.ngContent === 'object' && 'template' in overrides.ngContent) {
                ngContent = overrides.ngContent.template;
                overrides.ngContent.imports.forEach((imp) => imports.add(imp));
            }
            if (ngContent) defaultCode += `>${ngContent}\n</ui-${component?.slug}>`;
        } else defaultCode += '\n/>';
    }

    if (defaultCode || component.css) {
        imports.add('UICard');
        imports.add('Syntax');
    }

    if (component.exampleComponent) imports.add('NgComponentOutlet');

    fs.writeFileSync(
        outputPath,
        TEMPLATE({
            ...component,
            imports: Array.from(imports),
            phaseColor: COMPONENT_PHASE_COLORS[component.phase as ComponentPhase] || 'grey',
            defaultCode: defaultCode || '',
        }),
    );
}

function getDefaultInputValues(component: ComponentMeta): Record<string, any> {
    const defaultInputs: Record<string, any> = {};

    if (component.inputs.length) {
        for (const prop of component.inputs) {
            let value: any = prop.default;

            if (prop.required) {
                if (prop.type === 'string') {
                    value = 'example';
                }
            }

            if (!value) continue;

            if (prop.type === 'boolean') value = value === 'true' ? true : false;

            if (prop.type === 'number') value = Number(value);

            defaultInputs[prop.name] = value;
        }
    }

    return defaultInputs;
}
