import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { UITable } from './table';

@Component({
    selector: 'ui-table-example',
    standalone: true,
    imports: [CommonModule, UITable],
    template: `
        <h2>Table</h2>

        <p>Sortable columns with pagination.</p>

        <ui-table
            [title]="'U.S. States — Capitals & Quick Facts'"
            [size]="'medium'"
            [pageSize]="5"
            [columns]="[
                { key: 'state', label: 'State', width: '160px', sort: 'string' },
                { key: 'capital', label: 'Capital', width: '140px' },
                { key: 'population', label: 'Population', width: '140px', sort: 'number' },
                { key: 'nickname', label: 'Nickname', width: '1fr' },
            ]"
            [data]="[
                {
                    id: 'ca',
                    state: 'California',
                    capital: 'Sacramento',
                    population: 39512223,
                    nickname: 'The Golden State',
                },
                { id: 'ny', state: 'New York', capital: 'Albany', population: 19299981, nickname: 'The Empire State' },
                {
                    id: 'nj',
                    state: 'New Jersey',
                    capital: 'Trenton',
                    population: 8882190,
                    nickname: 'The Garden State',
                },
                { id: 'tx', state: 'Texas', capital: 'Austin', population: 29183290, nickname: 'The Lone Star State' },
                { id: 'hi', state: 'Hawaii', capital: 'Honolulu', population: 1415872, nickname: 'The Aloha State' },
                { id: 'ak', state: 'Alaska', capital: 'Juneau', population: 731545, nickname: 'The Last Frontier' },
                {
                    id: 'al',
                    state: 'Alabama',
                    capital: 'Montgomery',
                    population: 4903185,
                    nickname: 'The Heart of Dixie',
                },
                {
                    id: 'az',
                    state: 'Arizona',
                    capital: 'Phoenix',
                    population: 7151502,
                    nickname: 'The Grand Canyon State',
                },
                {
                    id: 'ar',
                    state: 'Arkansas',
                    capital: 'Little Rock',
                    population: 3011524,
                    nickname: 'The Natural State',
                },
                {
                    id: 'co',
                    state: 'Colorado',
                    capital: 'Denver',
                    population: 5773714,
                    nickname: 'The Centennial State',
                },
                {
                    id: 'ct',
                    state: 'Connecticut',
                    capital: 'Hartford',
                    population: 3605944,
                    nickname: 'The Constitution State',
                },
                { id: 'de', state: 'Delaware', capital: 'Dover', population: 989948, nickname: 'The First State' },
                {
                    id: 'fl',
                    state: 'Florida',
                    capital: 'Tallahassee',
                    population: 21477737,
                    nickname: 'The Sunshine State',
                },
                { id: 'ga', state: 'Georgia', capital: 'Atlanta', population: 10617423, nickname: 'The Peach State' },
                { id: 'ia', state: 'Iowa', capital: 'Des Moines', population: 3155070, nickname: 'The Hawkeye State' },
                { id: 'id', state: 'Idaho', capital: 'Boise', population: 1787065, nickname: 'The Gem State' },
                {
                    id: 'il',
                    state: 'Illinois',
                    capital: 'Springfield',
                    population: 12671821,
                    nickname: 'The Prairie State',
                },
                {
                    id: 'in',
                    state: 'Indiana',
                    capital: 'Indianapolis',
                    population: 6732219,
                    nickname: 'The Hoosier State',
                },
                { id: 'ks', state: 'Kansas', capital: 'Topeka', population: 2913314, nickname: 'The Sunflower State' },
                {
                    id: 'ky',
                    state: 'Kentucky',
                    capital: 'Frankfort',
                    population: 4467673,
                    nickname: 'The Bluegrass State',
                },
                {
                    id: 'la',
                    state: 'Louisiana',
                    capital: 'Baton Rouge',
                    population: 4648794,
                    nickname: 'The Pelican State',
                },
                { id: 'ma', state: 'Massachusetts', capital: 'Boston', population: 6892503, nickname: 'The Bay State' },
                { id: 'md', state: 'Maryland', capital: 'Annapolis', population: 6045680, nickname: 'The Free State' },
                { id: 'me', state: 'Maine', capital: 'Augusta', population: 1344212, nickname: 'The Pine Tree State' },
                {
                    id: 'mi',
                    state: 'Michigan',
                    capital: 'Lansing',
                    population: 9986857,
                    nickname: 'The Great Lakes State',
                },
                {
                    id: 'mn',
                    state: 'Minnesota',
                    capital: 'St. Paul',
                    population: 5639632,
                    nickname: 'The North Star State',
                },
                {
                    id: 'mo',
                    state: 'Missouri',
                    capital: 'Jefferson City',
                    population: 6137428,
                    nickname: 'The Show-Me State',
                },
                {
                    id: 'ms',
                    state: 'Mississippi',
                    capital: 'Jackson',
                    population: 2976149,
                    nickname: 'The Magnolia State',
                },
                { id: 'mt', state: 'Montana', capital: 'Helena', population: 1068778, nickname: 'The Treasure State' },
                {
                    id: 'nc',
                    state: 'North Carolina',
                    capital: 'Raleigh',
                    population: 10488084,
                    nickname: 'The Tar Heel State',
                },
                {
                    id: 'nd',
                    state: 'North Dakota',
                    capital: 'Bismarck',
                    population: 762062,
                    nickname: 'The Peace Garden State',
                },
                {
                    id: 'ne',
                    state: 'Nebraska',
                    capital: 'Lincoln',
                    population: 1934408,
                    nickname: 'The Cornhusker State',
                },
                {
                    id: 'nh',
                    state: 'New Hampshire',
                    capital: 'Concord',
                    population: 1359711,
                    nickname: 'The Granite State',
                },
                {
                    id: 'nm',
                    state: 'New Mexico',
                    capital: 'Santa Fe',
                    population: 2096829,
                    nickname: 'The Land of Enchantment',
                },
                {
                    id: 'nv',
                    state: 'Nevada',
                    capital: 'Carson City',
                    population: 3080156,
                    nickname: 'The Silver State',
                },
                { id: 'oh', state: 'Ohio', capital: 'Columbus', population: 11689100, nickname: 'The Buckeye State' },
                {
                    id: 'ok',
                    state: 'Oklahoma',
                    capital: 'Oklahoma City',
                    population: 3956971,
                    nickname: 'The Sooner State',
                },
                { id: 'or', state: 'Oregon', capital: 'Salem', population: 4217737, nickname: 'The Beaver State' },
                {
                    id: 'pa',
                    state: 'Pennsylvania',
                    capital: 'Harrisburg',
                    population: 12801989,
                    nickname: 'The Keystone State',
                },
                {
                    id: 'ri',
                    state: 'Rhode Island',
                    capital: 'Providence',
                    population: 1059361,
                    nickname: 'The Ocean State',
                },
                {
                    id: 'sc',
                    state: 'South Carolina',
                    capital: 'Columbia',
                    population: 5148714,
                    nickname: 'The Palmetto State',
                },
                {
                    id: 'sd',
                    state: 'South Dakota',
                    capital: 'Pierre',
                    population: 884659,
                    nickname: 'Mount Rushmore State',
                },
                {
                    id: 'tn',
                    state: 'Tennessee',
                    capital: 'Nashville',
                    population: 6833174,
                    nickname: 'The Volunteer State',
                },
                {
                    id: 'ut',
                    state: 'Utah',
                    capital: 'Salt Lake City',
                    population: 3205958,
                    nickname: 'The Beehive State',
                },
                { id: 'va', state: 'Virginia', capital: 'Richmond', population: 8535519, nickname: 'The Old Dominion' },
                {
                    id: 'vt',
                    state: 'Vermont',
                    capital: 'Montpelier',
                    population: 623989,
                    nickname: 'The Green Mountain State',
                },
                {
                    id: 'wa',
                    state: 'Washington',
                    capital: 'Olympia',
                    population: 7614893,
                    nickname: 'The Evergreen State',
                },
                { id: 'wi', state: 'Wisconsin', capital: 'Madison', population: 5822434, nickname: 'The Badger State' },
                {
                    id: 'wv',
                    state: 'West Virginia',
                    capital: 'Charleston',
                    population: 1792147,
                    nickname: 'The Mountain State',
                },
                { id: 'wy', state: 'Wyoming', capital: 'Cheyenne', population: 578759, nickname: 'The Equality State' },
            ]"></ui-table>
    `,
})
export class UITableExample {}
