/* eslint-disable @cspell/spellchecker */
import { CountryCode } from 'libphonenumber-js';
import * as Icons from '../lib/icons';
import { BspkIcon } from '../types/bspk-icon';

// Type definition for flag icons - use BspkIcon type which covers all icon components
export type FlagIconName = BspkIcon;

export type SupportedCountryCode = keyof CountryCodeData;

export type CountryCodeData = Omit<
    Record<CountryCode, { name: string; flagIconName: FlagIconName }>,
    | 'AC'
    | 'CI'
    | 'CV'
    | 'FM'
    | 'GP'
    | 'KN'
    | 'LC'
    | 'MF'
    | 'NC'
    | 'RE'
    | 'SH'
    | 'SJ'
    | 'TA'
    | 'VA'
    | 'VC'
    | 'WF'
    | 'XK'
    | 'YT'
>;

export const countryCodeData: CountryCodeData = {
    AD: { name: 'Andorra', flagIconName: Icons.IconFlagAndorra },
    AE: { name: 'United Arab Emirates', flagIconName: Icons.IconFlagUnitedArabEmirates },
    AF: { name: 'Afghanistan', flagIconName: Icons.IconFlagAfghanistan },
    AG: { name: 'Antigua and Barbuda', flagIconName: Icons.IconFlagAntiguaAndBarbuda },
    AI: { name: 'Anguilla', flagIconName: Icons.IconFlagAnguilla },
    AL: { name: 'Albania', flagIconName: Icons.IconFlagAlbania },
    AM: { name: 'Armenia', flagIconName: Icons.IconFlagArmenia },
    AO: { name: 'Angola', flagIconName: Icons.IconFlagAngola },
    AR: { name: 'Argentina', flagIconName: Icons.IconFlagArgentina },
    AS: { name: 'American Samoa', flagIconName: Icons.IconFlagAmericanSamoa },
    AT: { name: 'Austria', flagIconName: Icons.IconFlagAustria },
    AU: { name: 'Australia', flagIconName: Icons.IconFlagAustralia },
    AW: { name: 'Aruba', flagIconName: Icons.IconFlagAruba },
    AX: { name: 'Åland Islands', flagIconName: Icons.IconFlagAlandIsland },
    AZ: { name: 'Azerbaijan', flagIconName: Icons.IconFlagAzerbaijan },
    BA: { name: 'Bosnia and Herzegovina', flagIconName: Icons.IconFlagBosniaAndHerzegovina },
    BB: { name: 'Barbados', flagIconName: Icons.IconFlagBarbados },
    BD: { name: 'Bangladesh', flagIconName: Icons.IconFlagBangladesh },
    BE: { name: 'Belgium', flagIconName: Icons.IconFlagBelgium },
    BF: { name: 'Burkina Faso', flagIconName: Icons.IconFlagBurkinaFaso },
    BG: { name: 'Bulgaria', flagIconName: Icons.IconFlagBulgaria },
    BH: { name: 'Bahrain', flagIconName: Icons.IconFlagBahrain },
    BI: { name: 'Burundi', flagIconName: Icons.IconFlagBurundi },
    BJ: { name: 'Benin', flagIconName: Icons.IconFlagBenin },
    BL: { name: 'Saint Barthélemy', flagIconName: Icons.IconFlagSaintBarthelemy },
    BM: { name: 'Bermuda', flagIconName: Icons.IconFlagBermuda },
    BN: { name: 'Brunei', flagIconName: Icons.IconFlagBrunei },
    BO: { name: 'Bolivia', flagIconName: Icons.IconFlagBolivia },
    BQ: { name: 'Bonaire, Sint Eustatius and Saba', flagIconName: Icons.IconFlagBonaire },
    BR: { name: 'Brazil', flagIconName: Icons.IconFlagBrazil },
    BS: { name: 'Bahamas', flagIconName: Icons.IconFlagBahamas },
    BT: { name: 'Bhutan', flagIconName: Icons.IconFlagBhutan },
    BW: { name: 'Botswana', flagIconName: Icons.IconFlagBotswana },
    BY: { name: 'Belarus', flagIconName: Icons.IconFlagBelarus },
    BZ: { name: 'Belize', flagIconName: Icons.IconFlagBelize },
    CA: { name: 'Canada', flagIconName: Icons.IconFlagCanada },
    CC: { name: 'Cocos (Keeling) Islands', flagIconName: Icons.IconFlagCocosIslands },
    CD: { name: 'Democratic Republic of the Congo', flagIconName: Icons.IconFlagDemocraticRepublicOfTheCongo },
    CF: { name: 'Central African Republic', flagIconName: Icons.IconFlagCentralAfricanRepublic },
    CG: { name: 'Republic of the Congo', flagIconName: Icons.IconFlagRepublicOfTheCongo },
    CH: { name: 'Switzerland', flagIconName: Icons.IconFlagSwitzerland },
    CK: { name: 'Cook Islands', flagIconName: Icons.IconFlagCookIsland },
    CL: { name: 'Chile', flagIconName: Icons.IconFlagChile },
    CM: { name: 'Cameroon', flagIconName: Icons.IconFlagCameroon },
    CN: { name: 'China', flagIconName: Icons.IconFlagChina },
    CO: { name: 'Colombia', flagIconName: Icons.IconFlagColombia },
    CR: { name: 'Costa Rica', flagIconName: Icons.IconFlagCostaRica },
    CU: { name: 'Cuba', flagIconName: Icons.IconFlagCuba },
    CW: { name: 'Curaçao', flagIconName: Icons.IconFlagCuracao },
    CX: { name: 'Christmas Island', flagIconName: Icons.IconFlagChristmasIsland },
    CY: { name: 'Cyprus', flagIconName: Icons.IconFlagCyprus },
    CZ: { name: 'Czech Republic', flagIconName: Icons.IconFlagCzechRepublic },
    DE: { name: 'Germany', flagIconName: Icons.IconFlagGermany },
    DJ: { name: 'Djibouti', flagIconName: Icons.IconFlagDjibouti },
    DK: { name: 'Denmark', flagIconName: Icons.IconFlagDenmark },
    DM: { name: 'Dominica', flagIconName: Icons.IconFlagDominica },
    DO: { name: 'Dominican Republic', flagIconName: Icons.IconFlagDominicanRepublic },
    DZ: { name: 'Algeria', flagIconName: Icons.IconFlagAlgeria },
    EC: { name: 'Ecuador', flagIconName: Icons.IconFlagEcuador },
    EE: { name: 'Estonia', flagIconName: Icons.IconFlagEstonia },
    EG: { name: 'Egypt', flagIconName: Icons.IconFlagEgypt },
    EH: { name: 'Western Sahara', flagIconName: Icons.IconFlagWestSahara },
    ER: { name: 'Eritrea', flagIconName: Icons.IconFlagEritrea },
    ES: { name: 'Spain', flagIconName: Icons.IconFlagSpain },
    ET: { name: 'Ethiopia', flagIconName: Icons.IconFlagEthiopia },
    FI: { name: 'Finland', flagIconName: Icons.IconFlagFinland },
    FJ: { name: 'Fiji', flagIconName: Icons.IconFlagFiji },
    FK: { name: 'Falkland Islands', flagIconName: Icons.IconFlagFalklandIslands },
    FO: { name: 'Faroe Islands', flagIconName: Icons.IconFlagFaroeIslands },
    FR: { name: 'France', flagIconName: Icons.IconFlagFrance },
    GA: { name: 'Gabon', flagIconName: Icons.IconFlagGabon },
    GB: { name: 'United Kingdom', flagIconName: Icons.IconFlagUnitedKingdom },
    GD: { name: 'Grenada', flagIconName: Icons.IconFlagGrenada },
    GE: { name: 'Georgia', flagIconName: Icons.IconFlagGeorgia },
    GF: { name: 'French Guiana', flagIconName: Icons.IconFlagFrenchGuiana },
    GG: { name: 'Guernsey', flagIconName: Icons.IconFlagGuernsey },
    GH: { name: 'Ghana', flagIconName: Icons.IconFlagGhana },
    GI: { name: 'Gibraltar', flagIconName: Icons.IconFlagGibraltar },
    GL: { name: 'Greenland', flagIconName: Icons.IconFlagGreeland },
    GM: { name: 'Gambia', flagIconName: Icons.IconFlagGambia },
    GN: { name: 'Guinea', flagIconName: Icons.IconFlagGuinea },
    GQ: { name: 'Equatorial Guinea', flagIconName: Icons.IconFlagEquatorialGuinea },
    GR: { name: 'Greece', flagIconName: Icons.IconFlagGreece },
    GT: { name: 'Guatemala', flagIconName: Icons.IconFlagGuatemala },
    GU: { name: 'Guam', flagIconName: Icons.IconFlagGuam },
    GW: { name: 'Guinea-Bissau', flagIconName: Icons.IconFlagGuinea },
    GY: { name: 'Guyana', flagIconName: Icons.IconFlagGuyana },
    HK: { name: 'Hong Kong', flagIconName: Icons.IconFlagHongKong },
    HN: { name: 'Honduras', flagIconName: Icons.IconFlagHonduras },
    HR: { name: 'Croatia', flagIconName: Icons.IconFlagCroatia },
    HT: { name: 'Haiti', flagIconName: Icons.IconFlagHaiti },
    HU: { name: 'Hungary', flagIconName: Icons.IconFlagHungary },
    ID: { name: 'Indonesia', flagIconName: Icons.IconFlagIndonesia },
    IE: { name: 'Ireland', flagIconName: Icons.IconFlagIreland },
    IL: { name: 'Israel', flagIconName: Icons.IconFlagIsrael },
    IM: { name: 'Isle of Man', flagIconName: Icons.IconFlagIsleOfMan },
    IN: { name: 'India', flagIconName: Icons.IconFlagIndia },
    IO: { name: 'British Indian Ocean Territory', flagIconName: Icons.IconFlagIndianOceanTerritory },
    IQ: { name: 'Iraq', flagIconName: Icons.IconFlagIraq },
    IR: { name: 'Iran', flagIconName: Icons.IconFlagIran },
    IS: { name: 'Iceland', flagIconName: Icons.IconFlagIceland },
    IT: { name: 'Italy', flagIconName: Icons.IconFlagItaly },
    JE: { name: 'Jersey', flagIconName: Icons.IconFlagJersey },
    JM: { name: 'Jamaica', flagIconName: Icons.IconFlagJamaica },
    JO: { name: 'Jordan', flagIconName: Icons.IconFlagJordan },
    JP: { name: 'Japan', flagIconName: Icons.IconFlagJapan },
    KE: { name: 'Kenya', flagIconName: Icons.IconFlagKenya },
    KG: { name: 'Kyrgyzstan', flagIconName: Icons.IconFlagKyrgyzstan },
    KH: { name: 'Cambodia', flagIconName: Icons.IconFlagCambodia },
    KI: { name: 'Kiribati', flagIconName: Icons.IconFlagKiribati },
    KM: { name: 'Comoros', flagIconName: Icons.IconFlagComoros },
    KP: { name: 'North Korea', flagIconName: Icons.IconFlagNorthKorea },
    KR: { name: 'South Korea', flagIconName: Icons.IconFlagSouthKorea },
    KW: { name: 'Kuwait', flagIconName: Icons.IconFlagKuwait },
    KY: { name: 'Cayman Islands', flagIconName: Icons.IconFlagCaymanIslands },
    KZ: { name: 'Kazakhstan', flagIconName: Icons.IconFlagKazakhstan },
    LA: { name: 'Laos', flagIconName: Icons.IconFlagLaos },
    LB: { name: 'Lebanon', flagIconName: Icons.IconFlagLebanon },
    LI: { name: 'Liechtenstein', flagIconName: Icons.IconFlagLiechtenstein },
    LK: { name: 'Sri Lanka', flagIconName: Icons.IconFlagSriLanka },
    LR: { name: 'Liberia', flagIconName: Icons.IconFlagLiberia },
    LS: { name: 'Lesotho', flagIconName: Icons.IconFlagLesotho },
    LT: { name: 'Lithuania', flagIconName: Icons.IconFlagLithuania },
    LU: { name: 'Luxembourg', flagIconName: Icons.IconFlagLuxembourg },
    LV: { name: 'Latvia', flagIconName: Icons.IconFlagLatvia },
    LY: { name: 'Libya', flagIconName: Icons.IconFlagLibya },
    MA: { name: 'Morocco', flagIconName: Icons.IconFlagMorroco },
    MC: { name: 'Monaco', flagIconName: Icons.IconFlagMonaco },
    MD: { name: 'Moldova', flagIconName: Icons.IconFlagMoldova },
    ME: { name: 'Montenegro', flagIconName: Icons.IconFlagMontenegro },
    MG: { name: 'Madagascar', flagIconName: Icons.IconFlagMadagascar },
    MH: { name: 'Marshall Islands', flagIconName: Icons.IconFlagMarshallIslands },
    MK: { name: 'North Macedonia', flagIconName: Icons.IconFlagNorthMacedonia },
    ML: { name: 'Mali', flagIconName: Icons.IconFlagMali },
    MM: { name: 'Myanmar', flagIconName: Icons.IconFlagMyanmar },
    MN: { name: 'Mongolia', flagIconName: Icons.IconFlagMongolia },
    MO: { name: 'Macau', flagIconName: Icons.IconFlagMacau },
    MP: { name: 'Northern Mariana Islands', flagIconName: Icons.IconFlagNorthernMarianaIslands },
    MQ: { name: 'Martinique', flagIconName: Icons.IconFlagMartinique },
    MR: { name: 'Mauritania', flagIconName: Icons.IconFlagMauritania },
    MS: { name: 'Montserrat', flagIconName: Icons.IconFlagMontserrat },
    MT: { name: 'Malta', flagIconName: Icons.IconFlagMalta },
    MU: { name: 'Mauritius', flagIconName: Icons.IconFlagMauritius },
    MV: { name: 'Maldives', flagIconName: Icons.IconFlagMaldives },
    MW: { name: 'Malawi', flagIconName: Icons.IconFlagMalawi },
    MX: { name: 'Mexico', flagIconName: Icons.IconFlagMexico },
    MY: { name: 'Malaysia', flagIconName: Icons.IconFlagMalasia },
    MZ: { name: 'Mozambique', flagIconName: Icons.IconFlagMozambique },
    NA: { name: 'Namibia', flagIconName: Icons.IconFlagNamibia },
    NE: { name: 'Niger', flagIconName: Icons.IconFlagNiger },
    NF: { name: 'Norfolk Island', flagIconName: Icons.IconFlagNorfolkIsland },
    NG: { name: 'Nigeria', flagIconName: Icons.IconFlagNigeria },
    NI: { name: 'Nicaragua', flagIconName: Icons.IconFlagNicaragua },
    NL: { name: 'Netherlands', flagIconName: Icons.IconFlagNetherlands },
    NO: { name: 'Norway', flagIconName: Icons.IconFlagNorway },
    NP: { name: 'Nepal', flagIconName: Icons.IconFlagNepal },
    NR: { name: 'Nauru', flagIconName: Icons.IconFlagNauru },
    NU: { name: 'Niue', flagIconName: Icons.IconFlagNiue },
    NZ: { name: 'New Zealand', flagIconName: Icons.IconFlagNewZealand },
    OM: { name: 'Oman', flagIconName: Icons.IconFlagOman },
    PS: { name: 'Palestine', flagIconName: Icons.IconFlagPalestine },
    PA: { name: 'Panama', flagIconName: Icons.IconFlagPanama },
    PE: { name: 'Peru', flagIconName: Icons.IconFlagPeru },
    PF: { name: 'French Polynesia', flagIconName: Icons.IconFlagFrenchPolynesia },
    PG: { name: 'Papua New Guinea', flagIconName: Icons.IconFlagPapuaNewGuinea },
    PH: { name: 'Philippines', flagIconName: Icons.IconFlagPhilippines },
    PK: { name: 'Pakistan', flagIconName: Icons.IconFlagPakistan },
    PL: { name: 'Poland', flagIconName: Icons.IconFlagPoland },
    PM: { name: 'Saint Pierre and Miquelon', flagIconName: Icons.IconFlagSaintBarthelemy },
    PR: { name: 'Puerto Rico', flagIconName: Icons.IconFlagPuertoRico },
    PT: { name: 'Portugal', flagIconName: Icons.IconFlagPortugal },
    PW: { name: 'Palau', flagIconName: Icons.IconFlagPalau },
    PY: { name: 'Paraguay', flagIconName: Icons.IconFlagParaguay },
    QA: { name: 'Qatar', flagIconName: Icons.IconFlagQatar },
    RO: { name: 'Romania', flagIconName: Icons.IconFlagRomania },
    RS: { name: 'Serbia', flagIconName: Icons.IconFlagSerbia },
    RU: { name: 'Russia', flagIconName: Icons.IconFlagRussia },
    RW: { name: 'Rwanda', flagIconName: Icons.IconFlagRwanda },
    SA: { name: 'Saudi Arabia', flagIconName: Icons.IconFlagSaudiArabia },
    SB: { name: 'Solomon Islands', flagIconName: Icons.IconFlagSolomonIslands },
    SC: { name: 'Seychelles', flagIconName: Icons.IconFlagSeychelles },
    SD: { name: 'Sudan', flagIconName: Icons.IconFlagSudan },
    SE: { name: 'Sweden', flagIconName: Icons.IconFlagSweden },
    SG: { name: 'Singapore', flagIconName: Icons.IconFlagSingapore },
    SI: { name: 'Slovenia', flagIconName: Icons.IconFlagSlovenia },
    SK: { name: 'Slovakia', flagIconName: Icons.IconFlagSlovakia },
    SL: { name: 'Sierra Leone', flagIconName: Icons.IconFlagSierraLeone },
    SM: { name: 'San Marino', flagIconName: Icons.IconFlagSanMarino },
    SN: { name: 'Senegal', flagIconName: Icons.IconFlagSenegal },
    SO: { name: 'Somalia', flagIconName: Icons.IconFlagSomalia },
    SR: { name: 'Suriname', flagIconName: Icons.IconFlagSuriname },
    SS: { name: 'South Sudan', flagIconName: Icons.IconFlagSouthSudan },
    ST: { name: 'São Tomé and Príncipe', flagIconName: Icons.IconFlagSaoTomeAndPrincipe },
    SV: { name: 'El Salvador', flagIconName: Icons.IconFlagElSalvador },
    SX: { name: 'Sint Maarten', flagIconName: Icons.IconFlagSintMaarten },
    SY: { name: 'Syria', flagIconName: Icons.IconFlagSyria },
    SZ: { name: 'Eswatini', flagIconName: Icons.IconFlagEswatini },
    TC: { name: 'Turks and Caicos Islands', flagIconName: Icons.IconFlagTurksAndCaicos },
    TD: { name: 'Chad', flagIconName: Icons.IconFlagChad },
    TG: { name: 'Togo', flagIconName: Icons.IconFlagTogo },
    TH: { name: 'Thailand', flagIconName: Icons.IconFlagThailand },
    TJ: { name: 'Tajikistan', flagIconName: Icons.IconFlagTajikistan },
    TK: { name: 'Tokelau', flagIconName: Icons.IconFlagTokelau },
    TL: { name: 'Timor-Leste', flagIconName: Icons.IconFlagTimorLeste },
    TM: { name: 'Turkmenistan', flagIconName: Icons.IconFlagTurkmenistan },
    TN: { name: 'Tunisia', flagIconName: Icons.IconFlagTunisia },
    TO: { name: 'Tonga', flagIconName: Icons.IconFlagTonga },
    TR: { name: 'Turkey', flagIconName: Icons.IconFlagTurkey },
    TT: { name: 'Trinidad and Tobago', flagIconName: Icons.IconFlagTrinidadAndTobago },
    TV: { name: 'Tuvalu', flagIconName: Icons.IconFlagTuvalu },
    TW: { name: 'Taiwan', flagIconName: Icons.IconFlagTaiwan },
    TZ: { name: 'Tanzania', flagIconName: Icons.IconFlagTanzania },
    UA: { name: 'Ukraine', flagIconName: Icons.IconFlagUkraine },
    UG: { name: 'Uganda', flagIconName: Icons.IconFlagUganda },
    US: { name: 'United States of America', flagIconName: Icons.IconFlagUnitedStates },
    UY: { name: 'Uruguay', flagIconName: Icons.IconFlagUruguay },
    UZ: { name: 'Uzbekistan', flagIconName: Icons.IconFlagUzbekistan },
    VE: { name: 'Venezuela', flagIconName: Icons.IconFlagVenezuela },
    VG: { name: 'British Virgin Islands', flagIconName: Icons.IconFlagVirginIslandsBritish },
    VI: { name: 'United States Virgin Islands', flagIconName: Icons.IconFlagVirginIslands },
    VN: { name: 'Vietnam', flagIconName: Icons.IconFlagVietnam },
    VU: { name: 'Vanuatu', flagIconName: Icons.IconFlagVanuatu },
    WS: { name: 'Samoa', flagIconName: Icons.IconFlagSamoa },
    YE: { name: 'Yemen', flagIconName: Icons.IconFlagYemen },
    ZA: { name: 'South Africa', flagIconName: Icons.IconFlagSouthAfrica },
    ZM: { name: 'Zambia', flagIconName: Icons.IconFlagZambia },
    ZW: { name: 'Zimbabwe', flagIconName: Icons.IconFlagZimbabwe },
} as const;

export const countryCodes = Object.keys(countryCodeData) as SupportedCountryCode[];

/** Copyright 2026 Anywhere Real Estate - CC BY 4.0 */
