/**  generates the BspkIcon type used in the UI project
 * This type is a union of all icon component classes in the icons directory
 * 
 * $ npx tsx .scripts/generate-bspk-icon-type.ts  
*/

import * as fs from 'fs';
import * as path from 'path';

// Get the absolute path to the icons directory
const iconsDir = path.join(process.cwd(), 'projects/ui/src/lib/icons');
const iconDir = path.join(process.cwd(), 'projects/ui/src/lib/icon');

// Find all .ts files (icon components) in the icons directory
const iconFiles = fs
    .readdirSync(iconsDir)
    .filter(file => file.endsWith('.ts') && file !== 'index.ts');

const iconNames = iconFiles.map(file => file.replace(/\.ts$/, ''));

function toPascalCase(str: string) {
    return str
        .replace(/(^\w|-\w)/g, m => m.replace(/-/, '').toUpperCase())
        .replace(/(\d+)([a-zA-Z])/g, (_, num, chr) => num + chr.toUpperCase()) // Capitalize after numbers
        .replace(/([a-z])([A-Z]+)/g, (_, a, b) => a + b); // Preserve consecutive uppercase
}

const lines: string[] = [
    '// Auto-generated by .scripts/generate-icon-type.ts',
    "import * as Icons from '../projects/ui/src/lib/icons';",
    '',
    'export type BspkIcon =',
];

iconNames.forEach(iconNames => {
    const pascalName = toPascalCase(iconNames)
    lines.push(`  | typeof Icons.Icon${pascalName}`);
});

lines.push(';');

const outputPath = path.join(process.cwd(), 'projects/ui/src/types/bspk-icon.ts');
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, lines.join('\n'));
console.log('Generated BspkIcon type at', outputPath);