/**
 * Generates example components for each Example component (example.ts) in the UI library ("projects/ui/src/lib/*") and
 * creates a route file at "projects/demo/src/app/routes/generated.ts".
 *
 * $ npx tsx .scripts/generate-component-routes.ts
 */

// get a list of all example files

import { pretty, toPascalCase } from './utils';
import fs from 'fs';
import path from 'path';

const __dirname = path.dirname(new URL(import.meta.url).pathname);
const uiLibPath = path.join(__dirname, '../projects/ui/src/lib');

const getExamples = () =>
    fs
        // get all files and folders in ui lib
        .readdirSync(uiLibPath, { withFileTypes: true })
        // then filter to only folders that contain an example.ts file
        .filter((dirent) => dirent.isDirectory() && fs.existsSync(path.join(uiLibPath, dirent.name, 'example.ts')))
        // map out name (PascalCase of slug) and slug
        .map((dirent) => ({ name: toPascalCase(dirent.name), slug: dirent.name }));

// store examples to compare during watch
let examples = getExamples();

const importPath = (slug: string) => `../../../../../projects/ui/src/lib/${slug}/example`;

export function generateComponentRoutes() {
    examples = getExamples();

    const generatedRoutesPath = 'projects/demo/src/app/routes/generated.ts';

    fs.writeFileSync(
        path.join(__dirname, '..', generatedRoutesPath),
        `
/** Generated by generate-component-routes.ts */
import { NavRoute } from '../types';

export const componentItems: NavRoute[] = [
    { title: 'Components', section: true },${examples
        .map(
            // add an entry for each example
            ({ slug, name }) => `
    {
        path: '${slug}',
        loadComponent: () =>
            import('${importPath(slug)}').then((m) => m.UI${name}Example),
        title: '${name}',
    },`,
        )
        .join('')}
];
`,
    );

    pretty(path.join(__dirname, '..', generatedRoutesPath));

    console.log(`\n\x1b[32m✅ Generated component routes at projects/demo/src/app/routes/generated.ts 📄\x1b[0m\n`);
}

// if --write is provided, generate the routes once
if (process.argv.includes('--write')) {
    generateComponentRoutes();
}

// if --watch is provided, watch for changes to example.ts files in uiLibPath and re-run the script

if (process.argv.includes('--watch')) {
    console.log(`\x1b[33m👀 Watching for changes to example.ts files...\x1b[0m\n`);

    fs.watch(uiLibPath, { recursive: true }, () => {
        const examplesNow = getExamples();
        // we don't care about individual file changes, just whether the number of examples has changed or their slugs
        if (examplesNow.length !== examples.length || examplesNow.some((ex, i) => ex.slug !== examples[i].slug)) {
            console.log(
                `\n\x1b[33m🔄 Detected change to examples (${examples.length} => ${examplesNow.length}), regenerating component routes...\x1b[0m`,
            );
            generateComponentRoutes();
        }
    });
}
