/**
 * Generates example components for each component example `projects/demo/examples`.
 *
 * $ npx tsx .scripts/generate-component-routes.ts
 */

// get a list of all example files

import { execSync } from 'child_process';
import fs from 'fs';

const uniqueStr = (value: string, index: number, arr: string[]) => {
    return arr.indexOf(value) === index;
};

type ComponentMeta = {
    name: string;
    slug: string;
    type: 'component' | 'directive';
    classContent: string;
    template: string;
};

// GENERATE COMPONENT META

const componentMeta: ComponentMeta[] = [
    // {
    //     slug: 'icon',
    //     name: 'Icon',
    //     type: 'component',
    //     classContent: '',
    //     template: '<ui-icon name="add"></ui-icon>',
    // },
];

const EXAMPLES_DIR = 'projects/demo/examples';

fs.readdirSync(EXAMPLES_DIR).forEach((file) => {
    const [slug, _ext] = file.split('.');
    const content = fs.readFileSync(`${EXAMPLES_DIR}/${file}`).toString().trim();
    componentMeta.push({
        slug,
        name: `UI${slugToName(slug)}`,
        ...parseHtml(content),
    });
});

const componentsRoutesPath = 'projects/demo/src/app/routes/generated.ts';

// GENERATE COMPONENT ROUTES FILE

const componentsContent: string[] = [];

const fileImports = [`import { Component } from '@angular/core';`];

// Find all icon usages for [icon], [leadingIcon], [trailingIcon], leadingIcon:, trailingIcon:
function findIconComponentMatches(template: string): string[] {
    return [
        ...Array.from(template.matchAll(/\[icon\]="([\w]+)"/g)).map(m => m[1]),
        ...Array.from(template.matchAll(/\[leadingIcon\]="([\w]+)"/g)).map(m => m[1]),
        ...Array.from(template.matchAll(/\[trailingIcon\]="([\w]+)"/g)).map(m => m[1]),
        ...Array.from(template.matchAll(/leadingIcon:\s*([\w]+)/g)).map(m => m[1]),
        ...Array.from(template.matchAll(/trailingIcon:\s*([\w]+)/g)).map(m => m[1]),
    ];
}

componentMeta.forEach(({ name, slug, type, classContent, template }) => {
    if (type === 'component') {
        fileImports.push(`import { ${name} } from '../../../../../projects/ui/src/lib/${slug}';`);
    }

    if (type === 'directive') {
        fileImports.push(
            `import { ${name}Directive } from '../../../../../projects/ui/src/lib/${slug}/${slug}.directive';`,
        );
    }

    if (template.includes('handleClick')) {
    }

    const componentImports = Array.from(template.matchAll(/<ui-([a-z0-9-]+)( [^>]*)?>/g))
        .flatMap((m) => m[1])
        .map((slug) => `UI${slugToName(slug)}`);

    const icons = Array.from(template.matchAll(/<icon-([a-z0-9-]+)( [^>]*)?>/g))
        .flatMap((m) => m[1])
        .map((slug) => ({ slug, name: slugToName(slug) }));

    // import any icons (<icon-add></icon-add>)
    fileImports.push(
        ...icons.map(({ slug, name }) => {
            return `import { Icon${name} } from '../../../../../projects/ui/src/lib/icons/${slug}';`;
        }),
    );

    // look for used components
    const imports = [...componentImports, ...icons.map(({ name }) => `Icon${name}`)];

    // Find all icon usages for [icon], [leadingIcon], [trailingIcon]
    const iconComponentMatches = findIconComponentMatches(template);

// Add imports for detected icon components
iconComponentMatches.forEach(iconComp => {
    fileImports.push(
        `import { ${iconComp} } from '../../../../../projects/ui/src/lib/icons/${iconComp.replace(/^Icon/, '').replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '')}';`
    );
});

    if (slug)
        componentsContent.push(
            type === 'directive'
                ? directiveTemplate({ name, slug, template, imports })
                : componentTemplate({ name, slug, template, classContent, imports }),
        );

    
});

fs.writeFileSync(
    componentsRoutesPath,
    [
        `/** generated by generate-component-routes.ts */`,
        fileImports
            // remove duplicate imports
            .filter((line, index, arr) => line === '\n' || uniqueStr(line, index, arr))
            .join('\n'),
        `import { NavRoute } from '../types';`,
        ...componentsContent,
        `export const componentItems: NavRoute[] = [
  { title: 'Components', section: true },
  ${componentMeta
      .map(
          ({ name, slug }) =>
              `{ path: '${slug}', component: ${name}RouteComponent, title: '${name.replace(/^UI/, '')}' },`,
      )
      .join('\n  ')}
];`,
    ].join('\n'),
);

execSync(`npx prettier --write ${componentsRoutesPath}`);

function parseHtml(content: string): Omit<ComponentMeta, 'name' | 'slug'> {
    const metaRegex = /<!-- ([^:]+): (.*?) -->/g;
    const metaMatch = Array.from(content.matchAll(metaRegex));
    const meta: Record<string, string> = {};
    for (const match of metaMatch) {
        meta[match[1]] = match[2];
    }

    return {
        ...meta,
        type: meta.type === 'directive' ? 'directive' : 'component',
        classContent: meta.class || '',
        template: content.replace(/<!--.*?-->/g, '').trim(),
    };
}

type TemplateParams = {
    name: string;
    slug: string;
    template: string;
    classContent?: string;
    imports?: string[];
};

function componentTemplate({ name, slug, template, classContent, imports }: TemplateParams) {
    const hasHandleClick = template.includes('handleClick');
    // Find all icon usages for [icon], [leadingIcon], [trailingIcon]
    const iconComponentMatches = findIconComponentMatches(template);

    // Get existing public properties from classContent
    const existingProps = new Set<string>();
    if (classContent) {
        const matches = Array.from(classContent.matchAll(/public\s+(\w+)\s*=/g));
        matches.forEach(m => existingProps.add(m[1]));
    }

    // Only add public property if it doesn't already exist
    const uniqueIconComponentMatches = Array.from(new Set(iconComponentMatches));
const iconPublicProps = uniqueIconComponentMatches
    .filter(iconComp => !existingProps.has(iconComp))
    .map(iconComp => `public ${iconComp} = ${iconComp};`)
    .join('\n  ');

    return `
@Component({
  selector: '${slug}-route',
  standalone: true,
  imports: [${[name, ...(imports || [])].filter(uniqueStr).join(', ')}],
  template: \`${template}\`,
  styles: [
    \`
      :host {
        display: contents;
      }
    \`,
  ],
})
export class ${name}RouteComponent {${iconPublicProps}
${
        hasHandleClick
            ? `  handleClick() {
    console.log('${name} clicked!');
  }`
            : ''
    }
${classContent ? `\n${classContent}\n` : ''}}
`;
}

function directiveTemplate({ name, slug, template, imports }: TemplateParams) {
    return `
@Component({
  selector: '${slug}-route',
  imports: [${[...(imports || []), `${name}Directive`].join(', ')}],
  template: \`${template}\`,
  styles: [
    \`
      :host {
        display: contents;
      }
    \`,
  ],
})
export class ${name}RouteComponent {}
`;
}

function slugToName(slug: string) {
    return slug
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}
