/**
 * Generates example components for each Example component (example.ts) in the UI library ("projects/ui/src/lib/*") and
 * creates a route file at "projects/demo/src/app/routes/generated.ts".
 *
 * $ npx tsx .scripts/pre-build.ts
 */

// get a list of all example files

import { pretty, toPascalCase } from './utils';
import fs from 'fs';
import path from 'path';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

const uiLibPath = path.join(__dirname, '../projects/ui/src/lib');
const examples = fs
    // get all files and folders in ui lib
    .readdirSync(uiLibPath, { withFileTypes: true })
    // then filter to only folders that contain an example.ts file
    .filter((dirent) => dirent.isDirectory() && fs.existsSync(path.join(uiLibPath, dirent.name, 'example.ts')))
    // map out name (PascalCase of slug) and slug
    .map((dirent) => ({ name: toPascalCase(dirent.name), slug: dirent.name }));

const generatedRoutesPath = 'projects/demo/src/app/routes/generated.ts';

fs.writeFileSync(
    path.join(__dirname, '..', generatedRoutesPath),
    `
/** Generated by generate-component-routes.ts */${ex(
        // add an import for each example
        (slug, name) => `
import { UI${name}Example } from '../../../../../projects/ui/src/lib/${slug}/example';`,
    )}
import { NavRoute } from '../types';

export const componentItems: NavRoute[] = [
    { title: 'Components', section: true },${ex(
        // add an entry for each example
        (slug, name) => `
    { path: '${slug}', component: UI${name}Example, title: '${name}' },`,
    )}
];
`,
);

function ex(cb: (slug: string, name: string) => string): string {
    return examples.map(({ slug, name }) => cb(slug, name)).join('');
}

pretty(path.join(__dirname, '..', generatedRoutesPath));

console.log(`\n\x1b[32m✅ Generated component routes at projects/demo/src/app/routes/generated.ts 📄\x1b[0m\n`);
