/** Generates new projects/ui/src/index.ts with all exports from lib folder */
import * as fs from 'fs';
import * as path from 'path';

export function getIndexFileContent() {
    const __dirname = path.dirname(new URL(import.meta.url).pathname);

    const libDir = path.join(__dirname, '../projects/ui/src/lib');
    const servicesDir = path.join(__dirname, '../projects/ui/src/services');
    const indexPath = path.join(__dirname, '../projects/ui/src/index.ts');

    const exportLines: string[] = [];

    const libFiles = fs
        .readdirSync(libDir, { withFileTypes: true })
        .flatMap((dirent) => (dirent.isDirectory() ? [dirent.name] : []));

    exportLines.push(...libFiles.map((file) => `export * from './lib/${file}';`));

    const serviceFiles = fs
        .readdirSync(servicesDir, { withFileTypes: true })
        .map((dirent) => path.parse(dirent.name).name);

    console.log('serviceFiles', serviceFiles);

    exportLines.push(...serviceFiles.map((file) => `export * from './services/${file}';`));

    const indexContent = `/**
 * Public API Surface of UI library
 *
 * Generated by .scripts/update-index.ts
 */
${exportLines.join('\n')}
`;

    return { indexPath, indexContent };
}

export function updateIndex() {
    const { indexPath, indexContent } = getIndexFileContent();
    fs.writeFileSync(indexPath, indexContent);
    console.log('\x1b[32m✅ Updated index at ' + indexPath + ' 🎉\x1b[0m');
}

// if --write flag is provided, write the file
if (process.argv.includes('--write')) {
    updateIndex();
}
